### ISSUE TITLE
Request Vehicle Speed sensor be added

### ISSUE THREAD

**Issue by linuxkidd** [bretterer/home-assistant-rivian#108]
I'm curious if the `Vehicle Speed` is available in the API?  I know it's not presented in the mobile app ( at least not that I've found ).

If it is present, I'd love to have a `Vehicle Speed` sensor added to this integration!

Looking over the history of the code, it appears it had been [present at one point](https://github.com/bretterer/home-assistant-rivian/pull/11/files#diff-ebfd5cb251f7030c5c916c4d1f993f0bfcb2b96bcbafe357ad060b59e8d9600dR84-R91), but that was before the most recent API shift.

Thanks for all the work that's gone into the integration! :)

**Comment by jrgutier** [comment]
Yeah it's been unavailable for a while now and isn't exposed in the mobile client API.

**Comment by linuxkidd** [comment]
I suspected as much.. I guess I'll stick with calculating speed from the GPS position... Thanks!  I'll close this request for now.
