### ISSUE TITLE
How to configure the integration "device" for control?

### ISSUE THREAD

**Issue by poldim** [bretterer/home-assistant-rivian#116]
The release notes have the message below but I'm not clear on what to do after selecting my car.  The device list just says `No matching devices found`.

`** Note: To enable this feature, you need to configure the integration and select the vehicle(s) you want to enroll and have an available slot for a phone key, which is currently limited to 4 per vehicle.`

<img width="675" alt="image" src="https://github.com/bretterer/home-assistant-rivian/assets/16869713/fbcc6961-6fc2-4e8f-b849-b1ad3a0e0041">

**Comment by tmack8001** [comment]
You already had selected R1S, do you also have another device you would want to control? Looking in the background of your image the integration is only reporting "1 device" and that is already configured here.

**Comment by natekspencer** [comment]
You also have to have 2FA enabled as the error message states.

**Comment by tmack8001** [comment]
>  The device list just says No matching devices found.

This is to allow selecting a second vehicle if you had more than one.

**Comment by poldim** [comment]
> In this screenshot `R1S` as a device is already selected, do you also have another device you would want to control? Looking in the background of your image the integration is only reporting `1 device` and that is already configured here.

I didn't notice that the second device field only presented itself after the first one was selected.

> You also have to have 2FA enabled as the error message states.

Just added 2FA and successfully configured for control.  Going to try to see if I can configure something like I mentioned [here](https://github.com/bretterer/home-assistant-rivian/issues/105#issue-1751513542) (yet/already)
