### ISSUE TITLE
Charging Session Coordinator - Data leaks between vehicles

### ISSUE THREAD

**Issue by tmack8001** [bretterer/home-assistant-rivian#118]
For those that have 2+ vehicles an active charging session of one will populate the charging data to the other vehicle device.

<img width="1435" alt="image" src="https://github.com/bretterer/home-assistant-rivian/assets/2158627/424b5743-91f9-49c2-b8d7-a38476b3ea2c">
<img width="1438" alt="image" src="https://github.com/bretterer/home-assistant-rivian/assets/2158627/d8e1491f-841f-4b4a-bfaf-c14697f99647">

Whereas the vehicle state data published over the websocket is that only Sully (RB R1T) is charging and Mike (LG R1S) isn't even plugged in.

<img width="1003" alt="image" src="https://github.com/bretterer/home-assistant-rivian/assets/2158627/53393faf-3d58-4be3-b7fa-3394962aacac">

From the charging session API there is definitely different data as the attached files show. This leads me to believe there is a cross stream publishing where the charging coordinator doesn't remember the VIN associated to the charge session it is fetching, or something along those lines.

[r1s-charging.json.txt](https://github.com/bretterer/home-assistant-rivian/files/12452469/r1s-charging.json.txt)
[r1t-charging.json.txt](https://github.com/bretterer/home-assistant-rivian/files/12452470/r1t-charging.json.txt)

**Comment by tmack8001** [comment]
Unfortunately some of this seems to be related to backend Rivian API not providing the right filtered vehicle view for charging data to us.

For instance the mobile application *charging history* shows me only R1T sessions (and wallbox sessions) vs specifically sessions related to my selected vehicle.

**Comment by tmack8001** [comment]
![Screenshot_20230828-113926.png](https://github.com/bretterer/home-assistant-rivian/assets/2158627/3c9d6299-1342-4ce0-8455-040f7af301f6)

This was taken from the mobile app after selecting the R1S as my selected/active vehicle, but we haven't charged the S in over a month.

**Comment by tmack8001** [comment]
working with a rivian engineer, this seems to have stopped... so maybe fixed server side?

**Comment by bretterer** [comment]
@tmack8001 is this still stopped?  Can we close out the ticket?
