### ISSUE TITLE
Many sensors are showing as unavailable

### ISSUE THREAD

**Issue by OverZealous** [bretterer/home-assistant-rivian#12]
## What's Happening

A lot of the sensors configured by the integration always show _Unavailable_ now. See the screenshot below for a complete list.

I'm not entirely sure if this happened because of upgrading HomeAssistant, or if Rivian changed the API, but I figured I'd file an issue so it was known.

Note that I don't use any of the missing sensors, so this is **not** a priority for me.

## What I've tried

- Restarting HA
- Reloading the integration
- Setting up a new integration from scratch

## Versions
- Home Assistant: 2022.7.6
- Supervisor 2022.07.0
- Operating System 8.2
- Rivian Integration: 0.2.0

## Screenshot
Here's what my device looks like right now:
![Screen Shot 2022-07-22 at 11 04 14](https://user-images.githubusercontent.com/965719/180468645-caf4ccaf-53ad-44e0-89d5-295a001afe7d.png)

**Comment by jrgutier** [comment]
The access control on the API got restricted to what the Mobile App uses, and nothing else. I'm going to be working on getting the attributes that are allowed in HA, and that's it. Here' the list:

"$gnss",
"body/alarm/sound_alarm",
"body/closures/door_FL_locked_state",
"body/closures/door_FL_state",
"body/closures/door_FR_locked_state",
"body/closures/door_FR_state",
"body/closures/door_RL_locked_state",
"body/closures/door_RL_state",
"body/closures/door_RR_locked_state",
"body/closures/door_RR_state",
"body/closures/front_left_window_state",
"body/closures/front_right_window_state",
"body/closures/frunk_locked_state",
"body/closures/frunk_state",
"body/closures/gear_guard_locked_state",
"body/closures/liftgate_locked_state",
"body/closures/liftgate_state",
"body/closures/rear_left_window_state",
"body/closures/rear_right_window_state",
"body/closures/sidebin_L_locked_state",
"body/closures/sidebin_L_state",
"body/closures/sidebin_R_locked_state",
"body/closures/sidebin_R_state",
"body/closures/tailgate_locked_state",
"body/closures/tailgate_state",
"body/closures/tonneau_locked_state",
"body/closures/tonneau_state",
"body/door_control_log/BCM_WindowCalibrationFL_Status",
"body/door_control_log/BCM_WindowCalibrationFR_Status",
"body/door_control_log/BCM_WindowCalibrationRL_Status",
"body/door_control_log/BCM_WindowCalibrationRR_Status",
"body/wipers/fluid_state",
"core/ota_status/cgm_ota_install_fast_charging",
"core/ota_status/cgm_ota_install_hv_batt_low",
"core/ota_status/cgm_ota_install_not_parked",
"core/ota_status/cgm_ota_install_ready",
"core/power_modes/power_state",
"dynamics/hv_battery_notifications/BMS_thermal_event",
"dynamics/odometer/value",
"dynamics/powertrain_status/brake_fluid_level_low",
"dynamics/propulsion_status/PRNDL",
"dynamics/tires/tire_FL_pressure_status_valid",
"dynamics/tires/tire_FL_pressure_status",
"dynamics/tires/tire_FR_pressure_status_valid",
"dynamics/tires/tire_FR_pressure_status",
"dynamics/tires/tire_RL_pressure_status_valid",
"dynamics/tires/tire_RL_pressure_status",
"dynamics/tires/tire_RR_pressure_status_valid",
"dynamics/tires/tire_RR_pressure_status",
"energy_storage/charger/adjusted_soc",
"energy_storage/charger/EMS_charger_remainingtime_min_1",
"energy_storage/charger/vehicle_charger_state",
"energy_storage/icd_cid_notifications/b_pack_thermal_runaway_propagation",
"energy_storage/icd_cid_notifications/range_threshold",
"energy_storage/vehicle_energy/vehicle_range",
"telematics/ota_status/available_version_number",
"telematics/ota_status/available_version_week",
"telematics/ota_status/available_version_year",
"telematics/ota_status/available_version",
"telematics/ota_status/current_version_number",
"telematics/ota_status/current_version_week",
"telematics/ota_status/current_version_year",
"telematics/ota_status/current_version",
"telematics/ota_status/download_progress",
"telematics/ota_status/install_duration",
"telematics/ota_status/install_progress",
"telematics/ota_status/install_time",
"telematics/ota_status/install_type",
"telematics/ota_status/pending_reason_active_mode",
"telematics/ota_status/pending_reason_lv_batt",
"telematics/ota_status/pending_reason_other",
"telematics/ota_status/status_current",
"telematics/ota_status/status",
"thermal/hvac_cabin_control/cabin_temperature",
"thermal/hvac_cabin_control/driver_temperature",
"thermal/hvac_settings/pet_mode_status",
"thermal/hvac_settings/pet_mode_temperature_status",
"thermal/tmm_status/cabin_precondition_state",

**Comment by bretterer** [comment]
Thank you for the report!  As @jrgutier mentioned, they locked down the API.  We will be (@jrgutier mainly) has a PR in to fix things a bit and this should be merged and released this weekend
