### ISSUE TITLE
Charging sensors not working

### ISSUE THREAD

**Issue by WanderingStar** [bretterer/home-assistant-rivian#122]
Thanks for your work on this integration!

Prior to August 20th, the sensors in the `CHARGING_SENSORS` set worked for me.

<img width="1299" alt="image" src="https://github.com/bretterer/home-assistant-rivian/assets/1622203/0f011c84-4d28-4976-b0a8-f50a75074fb5">

Since then I have received no data (the sensors show as `Unknown`).

<img width="333" alt="image" src="https://github.com/bretterer/home-assistant-rivian/assets/1622203/0e0f03ff-5640-4b4f-a2cf-bbc51ab4f21b">

Unfortunately, I don't recall whether I updated the Rivian integration during that period. Is this problem limited to me, or are charging sensors broken for others?

**Comment by tmack8001** [comment]
We have noticed that charging sensor data isn't visible to `driver` profiles where it previously was available to both `driver` and `primary-owner` profiles.

Are you using a secondary account with the HA integration by chance?

**Comment by WanderingStar** [comment]
Yes, I set up a separate account for HA. I can try switching it to my Owner profile. I'll update with the results.

**Comment by WanderingStar** [comment]
No luck. Even charging after removing and re-installing the integration didn't result in any data.

**Comment by natekspencer** [comment]
> No luck. Even charging after removing and re-installing the integration didn't result in any data.

Did you switch to your owner profile for this? If so, can you also download the diagnostics file and post it? I have a single vehicle and am using my owner account and all the charging sensors are working fine for me.

**Comment by safadig** [comment]
Same here. Charging sensors not working. New install. Only one account

**Comment by WanderingStar** [comment]
Yes, I tried removing and re-installing the integration, logging in with my owner profile instead of the driver profile I created for HA. I don't have an option do download diagnostics as described [here](https://www.home-assistant.io/integrations/diagnostics/). Device Info just shows this:

<img width="334" alt="image" src="https://github.com/bretterer/home-assistant-rivian/assets/1622203/45f8370f-ba65-423e-8a6b-80a0ed986c7a">

I turned on debug logging for the integration, but it didn't turn up anything interesting. This was the only output that seemed to relate to charging.
```
2023-09-17 14:11:58.925 DEBUG (MainThread) [custom_components.rivian.coordinator] {'data': {'getLiveSessionData': {'__typename': 'LiveSessionData', 'power': None, 'startTime': None, 'kilometersChargedPerHour': None, 'currentPrice': None, 'totalChargedEnergy': None, 'rangeAddedThisSession': None, 'timeElapsed': None, 'currentCurrency': None}}}
```

**Comment by tmack8001** [comment]
After having a fix for this in the beta channel release, which isn't ready for prime time yet. I'll pulled forward this specific fix https://github.com/bretterer/home-assistant-rivian/pull/125 has the related backported code that does 2 things:

1. changes the param from using `vehicle.vin` and use `vehicle.vechicle_id` (an internal API attribute vs a public known value displayed on all windshields)
2. reduces the frequency of polling when vehicles aren't actively plugged in (why ask for charging data if the vehicle isn't plugged in so frequently - your welcome cloud servers and related ASGs)

**Comment by tmack8001** [comment]
From the PR I pushed I've successfully modified my local install and have these vehicle charger sensors back.

![Screenshot_20231013-114433.png](https://github.com/bretterer/home-assistant-rivian/assets/2158627/05ad07fd-fa14-4bc0-a9f3-c1de2ee2fc89)

**Comment by tmack8001** [comment]
https://github.com/bretterer/home-assistant-rivian/pull/125 for details

**Comment by safadig** [comment]
Fixed! Charging sensors all good

**Comment by tmack8001** [comment]
https://github.com/bretterer/home-assistant-rivian/releases/tag/0.10.8 will fix the "production" release of HA Rivian integration, the "beta" releases have fixed this for a while now which led to a delay in fixing the production release. Thanks for calling this one out to us @WanderingStar and @safadig we appreciate you for that and sticking with us as we debugged what was going on as the Rivian Cloud API changed a few things on us recently.

**Comment by WanderingStar** [comment]
Thanks, just wanted to confirm that this works for me!
