### ISSUE TITLE
Configuring total days of data

### ISSUE THREAD

**Issue by bplein** [bretterer/home-assistant-rivian#123]
Sorry if I couldn’t find it elsewhere.  My install is limited to about 10 days of data for SOC. How do I increase this value?  I have plenty of capacity, I’d love to keep many months of data from my truck.

**Comment by tmack8001** [comment]
10 days is the HA default, but is user selectable as per the [HA docs](https://www.home-assistant.io/integrations/recorder/#purge_keep_days).

**Comment by bplein** [comment]
Thank you. The Rivian stuff is why I finally got around to installing HA, Somu wasn't sure where it was kept.

**Comment by tmack8001** [comment]
No, problem. We don't mind questions like this as we don't expect everyone to know the details about HA 😉, adding a ticket here I hope helps someone in the future. We may also choose to highlight common questions and answers into the README.md for new users as well.
