### ISSUE TITLE
Getting Config flow could not be loaded Error

### ISSUE THREAD

**Issue by tyleratk** [bretterer/home-assistant-rivian#132]
My env: running Home Assistant using docker compose.

Using HACS I've added the custom repo, downloaded files through HACS, restarted, then when I go to add the integration I get the error "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble". I've attached the logs, but I assume the relevant line is

`ERROR (SyncWorker_8) [homeassistant.util.package] Unable to install package rivian-python-client==0.2.4: ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/.local'`. I've made sure the user that is running the container owns and has access to all the files in my docker folder. Is "/.local" the container or the machine docker is running on? Thank you!

[home-assistant_2023-11-26T16-24-21.072Z.log](https://github.com/bretterer/home-assistant-rivian/files/13467410/home-assistant_2023-11-26T16-24-21.072Z.log)

**Comment by natekspencer** [comment]
Unfortunately this looks like a docker/HACS issue and not an issue with this integration. I've not used docker compose to deploy either of them, so you're probably better off searching in HACS or the HA forums for recommendations.

**Comment by tyleratk** [comment]
I was able to solve this by running `sudo chown -R root:root <docker folder path>`
