### ISSUE TITLE
Bluetooth Pairing Timeout

### ISSUE THREAD

**Issue by AlanJohnWilliams** [bretterer/home-assistant-rivian#134]
Hi. Thanks for a terrific integration. Longtime Homeassistant user and a 2 week old R1t owner. I'm trying to setup the bluetooth pairing to enable vehicle control. My Homeassistant runs on HA OS on a proxmox host. I don't have a bluetooth adapter attached to the Homeassistant instance running in my basement, but I do have 2 ESPHome devices running HA bluetooth proxy. My HA instance shows up in the vehicle when I go to pair HA to my R1T, but the center console comes back with a generic failure message and a prompt to try again.

Do you know if the Rivian integration works over Bluetooth Proxy? Any pointers on where to look/enable debug messages?

Thanks!
-Alan

**Comment by jrgutier** [comment]
Proxy will work. That was the tested use case. I connected an
esphome inside the truck to get it to pair.

--

J.R. Gutierrez

**Comment by krazos** [comment]
For what it's worth, I've been having a similar issue, also on Proxmox VM. I am passing through a local Bluetooth adapter to the VM, which works with various Bluetooth based integrations, but will not pair with the Rivian. Admittedly, my Proxmox box is not all that close to the garage, so I also tried moving one of my (working) ESP32 Bluetooth proxies to the garage for pairing, and eventually tried connecting the Bluetooth proxy inside the truck, but no matter what, the truck never seems to see my HA instance. (I am pressing the Pair button in the Rivian device view to initiate pairing mode.)

**Comment by natekspencer** [comment]
If you enable debug logging and then attempt the pairing process, it'll help to try to understand where it is getting in the process before failing/timing out.

**Comment by jrgutier** [comment]
Local BT adapter connected to a VM did not work for me either. Abandoned it when I got BT Proxy working.

**Comment by AlanJohnWilliams** [comment]
Thanks for confirming this should work over Bluetooth proxy. So far no luck and nothing obvious in any of the logs, but I'll keep digging.

**Comment by AlanJohnWilliams** [comment]
Upgraded to beta 18 and then noticed the "pair" button entity in HA. Pressing that did the trick to get the truck to pair. Not sure how I missed that in the release notes. Thanks!
