### ISSUE TITLE
Feature Request: Toggle Accessory Dock Locking

### ISSUE THREAD

**Issue by ksheyman** [bretterer/home-assistant-rivian#145]
Hello, I have [XCDShop's Rivian Camp Speaker Replacement Safe with Fingerprint Reader](https://www.etsy.com/shop/XCDShop?ref=l2-about-shopname). As the name suggests, this safe replaces the Rivian Camp Speaker and can be locked in place like the OEM speaker. Since the accessory dock unlocks when parked, I would like to use the Rivian HA integration to automatically re-lock it whenever it unlocks. Thank you for your consideration.

**Comment by natekspencer** [comment]
Unfortunately, until similar functionality is added to the official Rivian app, the ability to do this in HA will be unavailable. I'm going to close this request for now since it is not possible.
