### ISSUE TITLE
REST_FORBIDDEN error when logging in

### ISSUE THREAD

**Issue by Ratchicken** [bretterer/home-assistant-rivian#152]
When I try to setup the integration I get a REST_FORBIDDEN error when trying to log in.  Did something break recently or am I missing some configuration in my account?

**Comment by natekspencer** [comment]
Without additional context or error logs, it's hard to say whether that error is coming from Rivian, github or otherwise.

**Comment by Ratchicken** [comment]
I tried again this evening and the error went away.
