### ISSUE TITLE
Feature Request: Open/Close Tonneau Cover and Charge Port? 

### ISSUE THREAD

**Issue by TonyMontuna** [bretterer/home-assistant-rivian#171]
Not sure if this is the best place but wanted to ask if there is anything on the roadmap for opening and closing the tonneau cover and charging port door? 

Would be a really great feature for the community. 

TY

**Comment by natekspencer** [comment]
Open/Close Tonneau Cover should already exist. You have to have vehicle controls enabled which means pairing your HA instance with your truck. Opening/closing charge port can not be implemented at this time as there is no way to do it in the mobile app that we've discovered.

**Comment by TonyMontuna** [comment]
Hi Nathan, appreciate you getting back to me so quicky, I don't see the tonneau cover controls under the script creation drop down. Is it somewhere else? I see a ton of other controls, which I'm using a bunch of, but nothing specific for the tonneau cover. Any help would be appreciated. 


![image](https://github.com/user-attachments/assets/6c5a37d9-8d74-4784-8cb4-5c2e827a9eb9)

**Comment by natekspencer** [comment]
Can you look for the tonneau cover in your entities? Not everything always shows up in that list.

**Comment by TonyMontuna** [comment]
I really really appreciate your help with this. 

I found these but they're binary sensors without any control functionality 

![image](https://github.com/user-attachments/assets/cd582e33-2552-4077-b87a-f8eb1868429f)

**Comment by natekspencer** [comment]
Can you download the diagnostics file and post that?

**Comment by natekspencer** [comment]
And just to cover my bases, you do have a powered tonneau, yes? And can you open/close it in the Rivian app? (I don't actually have a powered tonneau to test myself)

**Comment by TonyMontuna** [comment]
Confirmed, I do have a powered tonneau cover. It didn't initially come with the truck on delivery, but rivian installed it about a month ago now. Here are the diagnostics: 

[config_entry-rivian-b1e6bf6a2d764dc3504cd5186f9560fa.json](https://github.com/user-attachments/files/16552787/config_entry-rivian-b1e6bf6a2d764dc3504cd5186f9560fa.json)

**Comment by natekspencer** [comment]
Ok, now I need to know how you got one installed and how I can do the same!

Looking at the diagnostics, I'm not seeing a `TONNEAU_CMD` supported feature, which is what we use in the code to determine if open/close tonneau is supported. I'll look through your diagnostics file a little more and see if there is anything in there that can help us determine if you have a powered tonneau to enable that.

**Comment by krazos** [comment]
FWIW, I also have an R1T with a factory-installed powered tonneau cover, but I do not have a `cover` entity for the tonneau cover either. (Nor do I see an option to control the tonneau cover in the app.) This [Reddit post](https://www.reddit.com/r/Rivian/comments/1eff8bj/control_tonneau_through_the_phone_app/) indicates that app control is not available for the tonneau cover.

**Comment by TonyMontuna** [comment]
haha! I had it on my build sheet, so I was very surprised when I showed up to pick up the truck they gave me a document to sign that said "we promise to install it within 6 months". Which they did. If you had one on your build sheet, I'd reach out to the Rivian support guides and tell them you want your tonneau cover installed and they should set you up with a service appointment to get it done. Takes about a day or two to install. If you didn't have it on your build sheet, I'm not sure if they're doing installs after delivery but I'd contact your guide or customer support and see if you can purchase one. 

That being said, please let me know if you find anything in the diagnostics for the cover! Would be really cool to have on my HASS instance instead of using the app or the button on the truck bed. 

Thanks again for your help with the Nathan!

**Comment by natekspencer** [comment]
Thanks @krazos for that post and your knowledge. It looks like the functionality does not exist via the app at the moment. I can no longer find the feature flag check in the android app either. Unfortunately, @TonyMontuna, it will not be available in HA at this time.

**Comment by TonyMontuna** [comment]
Thanks all for the knowledge. 

I wonder what happened, cause it seems like this was at one time a feature no? Or am I crazy @natekspencer

**Comment by natekspencer** [comment]
I thought it was, but again, I never had one myself to actually be able to test. I just enabled the functionality via the same feature flags I found in the app at the time. If you ever do see it appear in the app, please feel free to open up a feature request. Until then, I'm gonna close this issue since it doesn't seem to be possible currently.
