### ISSUE TITLE
Battery Drain While Enabled

### ISSUE THREAD

**Issue by TECHeSmurf** [bretterer/home-assistant-rivian#178]
Just curious if anyone else is seeing 2 to 4 precent battery loose per day while the integration is active?  I have a Gen 1 R1T running 2024.31.01. 

The truck will be in the Sleep state for ~10 hours then change to Ready for ~2 hours. Then the cycle repeats.

**Comment by Noerr** [comment]
I see that rate of discharge without having gotten around to trying this integration yet.  The energy loss sucks.

**Comment by natekspencer** [comment]
Unless you've enabled vehicle controls and are automating/triggering wake or other commands to your vehicle, you're just seeing what is happening with your vehicle as reported by Rivian. That sleep cycle will happen with or without this integration running.

**Comment by TECHeSmurf** [comment]
No vehicle controls enabled, as far as I know.  I am not connecting via Bluetooth from my HA. 

I was hoping there would be minimal vehicle chatter, but I disabled the integration last night as my "final" test, and I had zero percentage loss.  I unplugged at 19:00 with 75% and went to work this morning at 07:30 with it showing 75% still.  I am a firm believer in Science is repeatable, so I am going to Enable the integration tonight to see what it does.

Thanks for the responses!

**Comment by tmack8001** [comment]
HA doesn't communicate directly with the vehicle at all for state monitoring. HA creates a single persistent websocket connection to the Rivian cloud API in which the truck itself chooses when to communicate with and that is the source of all read data signals. 

Let us know how it goes.

**Comment by TECHeSmurf** [comment]
So overnight with the integration enabled, I once again lost 2%.  If this is not directly talking to the truck I do not understand.  With that said, I just realized I was running 1.3.1 of the integration and have since updated to 1.3.3.  Will report back tomorrow.

**Comment by bretterer** [comment]
@TECHeSmurf as @tmack8001 said, The integration does not affect phantom drain unless you are enabling controls, which it seems you are not.  We are not communicating with the vehicle directly, but rather just the API server at Rivian.  We have done many tests around this and notice the same phantom drain with our without the HA integration running.

**Comment by poldim** [comment]
@TECHeSmurf - it's hard to have a good amount of data over a single day, try to do it over a larger window, maybe when you're out of town)

[Personally, I'm seeing close to 4% phantom drain](https://www.rivianforums.com/forum/threads/anyone-using-rivian-unofficial-integration-with-home-assistant.22700/post-555067).  I understand that based on the architecture in which the data is pulled from AWS services it shouldn't have an impact on the car.  Maybe I'll try disabling it the next time I leave it at the airport to confirm this point.  It sounds like the culprit _might_ be that the car is waking itself to allow the HV pack to charge my small 12V battery.

**Comment by TECHeSmurf** [comment]
Hey @poldim , Yes I have tried for multiple days, actually back to August, and it is approximately the same pattern.

Now I did have the truck at the airport last week with the integration disabled and for the 4.5 days I lost ~8%.  So same with and without the integration enabled.  So, I feel better there that I can continue to use and that is not the culprit of the drain (as others had suggested that the drain is not from HA).

I do like the 12v theory, as that is something I also have thought of recently.  I know my truck is always running something due to behavior I have witnessed with the truck sensing the presence of the key fob when 1. I do not have unlock turned on at home.  2. The key fob is not even a remote unlock device in the settings.

In any case I have an appointment in the next week or so.

Thank you for all the help and support!!

**Comment by bretterer** [comment]
It's great news that you've determined the issue isn't related to our integration. If you have any further questions or concerns, please don't hesitate to reach out. We're happy to help in any way we can!

**Comment by poldim** [comment]
> Hey @poldim , Yes I have tried for multiple days, actually back to August, and it is approximately the same pattern.
> 
> Now I did have the truck at the airport last week with the integration disabled and for the 4.5 days I lost ~8%. So same with and without the integration enabled. So, I feel better there that I can continue to use and that is not the culprit of the drain (as others had suggested that the drain is not from HA).

I've also noticed that if I go into the garage, the truck wakes up.  I have PAAK disabled at home and the car stays unlocked (as it should in the garage, handles popped out).  Not sure if it's just detecting motion through cameras, other sensors or how/why else it's waking.

> I do like the 12v theory, as that is something I also have thought of recently. I know my truck is always running something due to behavior I have witnessed with the truck sensing the presence of the key fob when 1. I do not have unlock turned on at home. 2. The key fob is not even a remote unlock device in the settings.
Some good discussion on this subject here: https://www.rivianforums.com/forum/threads/sleep-and-idle-modes-what-happens-during-idle-and-can-we-prevent-it.20588/
