### ISSUE TITLE
Support for Multiple VIN

### ISSUE THREAD

**Issue by tmack8001** [bretterer/home-assistant-rivian#20]
Adding support and logic to allow for querying for multiple VIN (vehicles) for those that have multiple.
Though for some households this may require multiple Rivian credentials (one partner bought one the other partner bought the second).

Not super urgent I'm sure those that have multiple can wait for this support 🤣

**Comment by OverZealous** [comment]
One possible way to solve this is to simply allow changing the prefix used for the sensors.

Rivian doesn't allow naming our vehicles yet, like Tesla, but if we could just change `rivian_*` to `truckymctruckface_*`, then I believe it would be possible to have multiple copies of the same integration set up.

I could be wrong on this front, though, I've only ever had multiple integrations for things like Roku, which are usually automatically detected.

**Comment by tmack8001** [comment]
Probably best to use VIN (or vehicle ID) since names could change over time requiring all integrations, dashboards and automations to be rewritten whereas the VIN (or vehicle ID) will never change.

Also I want to explore sensor groups for things like "lock/unlock" so users don't need to do `front left || front right || rear left || rear right || ...` to have an integration/automation to warn them about a random door being left unlocked (or open).

**Comment by bretterer** [comment]
We may also need to allow two fully different configurations.   if a family has multiple Rivians, but not all Rivians share a driver profile, we will have to allow logging in from different profiles

**Comment by OverZealous** [comment]
That’s a good idea. I’m pretty sure we’re going to end up with our trucks on 2 different accounts. At the same time, I was planning on just inviting my HA account to both vehicles.

**Comment by tmack8001** [comment]
We will have the truck on one and the SUV on the other ourselves.

Though yes inviting the same account to both should be fairly common place.

**Comment by natekspencer** [comment]
Fixed via #88
