### ISSUE TITLE
Driver Temperature sensor stuck at 32 degrees Fahrenheit

### ISSUE THREAD

**Issue by krazos** [bretterer/home-assistant-rivian#23]
For the past several days, my Driver Temperature sensor has been stuck at 32 degrees Fahrenheit. I have tried reloading the integration, restarting Home Assistant, etc. 

![image](https://user-images.githubusercontent.com/18428022/198879116-017a9f0a-0bfd-46eb-a4bf-4f68818fdef2.png)

**Comment by jrgutier** [comment]
It's the same here. This is what the Rivian is supplying to the integration. I think it's the default value. We can switch it to unavailable if it's 32. It obfuscates what's really happening though.

**Comment by krazos** [comment]
Do you know what the Driver Temperature sensor is intended to capture, and how it differs from the Cabin Temperature sensor?

**Comment by patfreeman** [comment]
> Do you know what the Driver Temperature sensor is intended to capture, and how it differs from the Cabin Temperature sensor?

That is the set temperature for the driver side of the cabin.

**Comment by krazos** [comment]
> > Do you know what the Driver Temperature sensor is intended to capture, and how it differs from the Cabin Temperature sensor?
> 
> That is the set temperature for the driver side of the cabin.

Thanks. In that case, unless/until we gain the ability to change this parameter via the API, I will likely disable or hide this sensor in Home Assistant as I do not anticipate needing to view the current setting.

**Comment by bretterer** [comment]
This appears to be fixed... If it is still an issue for you, please feel free to re-open this ticket
