### ISSUE TITLE
[Request] Location Tracker

### ISSUE THREAD

**Issue by OverZealous** [bretterer/home-assistant-rivian#3]
I'm not sure if Rivian exposes this in a way that can be added to HA, but it would be nice to have a vehicle location tracker.

**Comment by bretterer** [comment]
Thanks for the suggestion.  I do have access to the $GSNN properties, but need to figure out what kind of sensor to add for that.  I'd love to just integrate it directly onto a map, but may have to just have lat and lon sensors

**Comment by OverZealous** [comment]
I think the lat/long are what you need to create a location tracker.

I bet you can figure out the [right thing from the Tesla integration](https://github.com/alandtse/tesla), since they have that working.

[Looks like it might all be contained in this file.](https://github.com/alandtse/tesla/blob/dev/custom_components/tesla_custom/device_tracker.py)

**Comment by bretterer** [comment]
Resolved by #5 

Will be released in version [0.0.1-beta.2](https://github.com/bretterer/home-assistant-rivian/releases/tag/0.0.1-beta.2)
