### ISSUE TITLE
Unable to lookup cesium.rivianservices.com

### ISSUE THREAD

**Issue by OverZealous** [bretterer/home-assistant-rivian#37]
Apparently cesium is no longer a valid domain for Rivian? (I really wish they would just provide an official, supported API.)

I know technically I should have submitted this to the other repo, but I thought it might get more visibility here. Interestingly, looking at my DNS logs, the app appears to be only looking for `rivian.com` directly.

The plugin stopped today with this error:

```
This error originated from a custom integration.

Logger: custom_components.rivian
Source: custom_components/rivian/__init__.py:156
Integration: Rivian (Unofficial) (documentation)
First occurred: 6:08:12 PM (1964 occurrences)
Last logged: 9:12:29 PM

Unknown Exception while updating Rivian data: Error occurred while communicating with Rivian.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 860, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/rivian/rivian.py", line 264, in get_vehicle_info
    response = await self._session.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host cesium.rivianservices.com:443 ssl:default [Name does not resolve]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/rivian/__init__.py", line 156, in _update_api_data
    vehicle_info = await self._api.get_vehicle_info(
  File "/usr/local/lib/python3.10/site-packages/rivian/rivian.py", line 275, in get_vehicle_info
    raise Exception(
Exception: Error occurred while communicating with Rivian.
```

**Comment by OverZealous** [comment]
Actually, the app is also looking for `tsync.rivianservices.com` and `ruploader-asset.rivianservices.com` (though I assume the latter is irrelevant).

**Comment by jrgutier** [comment]
Yeah, I can confirm cesium is dead. Even the previous IP addresses don't allow any connections. It's always on a Friday they do this.

**Comment by bretterer** [comment]
We have been working to get this resolved.  I believe I have the code working again with location and a single sensor.  We are working as quick as possible to get the other sensors back online, but the switch over to GraphQL will cause us to lose access to a few items.

Here is where were at right now
<img width="1043" alt="Screen Shot 2023-01-09 at 9 31 36 PM" src="https://user-images.githubusercontent.com/1906920/211448648-4b3af15b-bc32-4e5a-9298-9186f2270bf7.png">

Thank you for sticking with us while we work to resolve the issue!

**Comment by OverZealous** [comment]
That's great news! For me, personally, the battery level & location are the most useful. Anything else is just icing.

**Comment by bretterer** [comment]
This is now resolved in https://github.com/bretterer/home-assistant-rivian/releases/tag/0.7.0-beta.1.   Please update to the latest version

**Comment by OverZealous** [comment]
Seems to be working great for me!

I'll have to see if I can figure out a new way to determine if the truck is plugged in or not. I was using `rivian_energy_storage_charger_ems_charger_evse_type`, but that seems to no longer be available. But other than that, it's nice having the data back!

Thank you all very much for working on this.

**Comment by tmack8001** [comment]
I'm updating some of my pre-canned dashboard I shared based on the new sensor naming that went into this release.

To have a simple "charging" or "not charging" check out `Charging Status` as shown below in the `Logbook` card (best way to see all sensor modifications and discover new data points).

<img width="353" alt="image" src="https://user-images.githubusercontent.com/2158627/211845157-27cc3ff8-a192-4df7-bd0b-b4de60736f47.png">

**Comment by OverZealous** [comment]
I have charging/not charging, but I also like to track plugged in but not charging. My one alert is a reminder if the truck is not plugged in and the power is below 50%.

Sometimes with scheduled departure on my Tesla, it'll be plugged in and low, but not actively charging as it's waiting to charge until later. This is less of a concern on the Rivian, since it doesn't have scheduled departure (and I don't use time-of-day charging).

I just did some checking, it doesn't appear that there's information available right now to detect it, but that's OK, it's not critical. They are providing it to the app somehow, as it knows if it's plugged in and not charging on the graphic.

**Comment by tmack8001** [comment]
There are some prior sensors we haven't been able to reverse engineer into the new GraphQL API language. This is indeed one of those sensors. Likely it is still available for us, but with the new API we need to know the direct name of the sensor and there isn't a wild card or even a documented way to determine the name. Bare with us as we try to find what this sensor is 👍 .

**Comment by tmack8001** [comment]
Actually I stand corrected we are using a different sensor/attribute that is provided to us... forgot about this mapping.

Try to convert to using `binary_sensor.rivian_energy_storage_charger_status_vehicle_charger_status` which will be able to determine this for you @OverZealous

**Comment by OverZealous** [comment]
Oh yeah, no worries! I'm totally happy with what you have gotten working. Reverse engineering this is frustrating to say the least, I'm sure.

I'm pretty blown away by what you guys have done already. I love having this as part of my HA setup.

I'll check out out that new sensor when it pops up. Thanks!
