### ISSUE TITLE
0.7.0-beta1 User Account Locked

### ISSUE THREAD

**Issue by tmack8001** [bretterer/home-assistant-rivian#44]
Due to likely too many simutaneous sessions being created through the GraphQL authenticate request Rivian accounts are being locked temporarily not allowing authentication (Rivian.com or Mobile App Logins will fail). Existing sessions don't seem to be interrupted... so app functions should still be available to HA users that opted to run the 0.7.0-beta1 today.

HA system logs like the following would be seen upon each and every refresh of the data sensors.

```
Logger: custom_components.rivian
Source: custom_components/rivian/__init__.py:236
Integration: Rivian (Unofficial) ([documentation](https://github.com/bretterer/home-assistant-rivian))
First occurred: 9:36:57 AM (2529 occurrences)
Last logged: 5:45:42 PM

Unexpected error fetching rivian data: Error communicating with API
Traceback (most recent call last):
  File "/config/custom_components/rivian/__init__.py", line 170, in _update_api_data
    vehicle_info = await self._api.get_vehicle_state(
  File "/usr/local/lib/python3.10/site-packages/rivian/rivian.py", line 438, in get_vehicle_state
    return await self.__graphql_query(headers, url, graphql_json)
  File "/usr/local/lib/python3.10/site-packages/rivian/rivian.py", line 509, in __graphql_query
    raise Exception(
Exception: Error occurred while reading the graphql response from Rivian.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/rivian/__init__.py", line 220, in _async_update_data
    return await self._update_api_data()
  File "/config/custom_components/rivian/__init__.py", line 215, in _update_api_data
    raise Exception("Error communicating with API") from err
Exception: Error communicating with API

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/rivian/__init__.py", line 236, in _async_update_data
    raise Exception("Error communicating with API") from err
Exception: Error communicating with API
```

```
Logger: custom_components.rivian
Source: custom_components/rivian/__init__.py:215
Integration: Rivian (Unofficial) ([documentation](https://github.com/bretterer/home-assistant-rivian))
First occurred: 9:36:57 AM (2529 occurrences)
Last logged: 5:45:42 PM

Unknown Exception while updating Rivian data: Error communicating with API
Traceback (most recent call last):
  File "/config/custom_components/rivian/__init__.py", line 170, in _update_api_data
    vehicle_info = await self._api.get_vehicle_state(
  File "/usr/local/lib/python3.10/site-packages/rivian/rivian.py", line 438, in get_vehicle_state
    return await self.__graphql_query(headers, url, graphql_json)
  File "/usr/local/lib/python3.10/site-packages/rivian/rivian.py", line 509, in __graphql_query
    raise Exception(
Exception: Error occurred while reading the graphql response from Rivian.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/rivian/__init__.py", line 220, in _async_update_data
    return await self._update_api_data()
  File "/config/custom_components/rivian/__init__.py", line 215, in _update_api_data
    raise Exception("Error communicating with API") from err
Exception: Error communicating with API
```

```
Logger: custom_components.rivian
Source: custom_components/rivian/__init__.py:161
Integration: Rivian (Unofficial) ([documentation](https://github.com/bretterer/home-assistant-rivian))
First occurred: 2:11:16 PM (2510 occurrences)
Last logged: 5:45:42 PM

Unknown Exception while updating Rivian data: Error occurred while reading the graphql response from Rivian.
Traceback (most recent call last):
  File "/config/custom_components/rivian/__init__.py", line 161, in _update_api_data
    auth = await self._api.authenticate_graphql(
  File "/usr/local/lib/python3.10/site-packages/rivian/rivian.py", line 356, in authenticate_graphql
    response = await self.__graphql_query(headers, url, graphql_json)
  File "/usr/local/lib/python3.10/site-packages/rivian/rivian.py", line 509, in __graphql_query
    raise Exception(
Exception: Error occurred while reading the graphql response from Rivian.
```

**Comment by tmack8001** [comment]
Seems this may lock one out after 4 hours on running the new beta version due to the number of simultaneous sessions created. Locks that I've seen happen in the past have lasted ~24hr. 

Best to setup a second "driver" account for keeping your "production"/"primary" account clean and only associated to the Mobile Application / Rivian.com usage.

**Comment by dag10** [comment]
Thanks, I really appreciate the heads up about this risk.

For anyone else who wants to set up a separate account for this integration, here's what I did:
1) Open the app, go to **Drivers and keys** and click **Manage**, then **Invite a driver**.
2) Enter an email address separate from your main account. If you use gmail, you can actually use an alias to your existing email, in the format of `myrealemail+homeassistant@gmail.com` and all emails to that will get forwarded to your real one.
3) When you get the invitation email, right click **Accept invite** and open it in an Incognito Tab to make sure you're not already signed into rivian.com with your real account. Then it'll prompt you to make a new account for your car. I just chose first name "Home" and last name "Assistant" for simplicity.
4) I reconfigured the integration with the new account credentials and it worked perfectly :)

**Comment by tmack8001** [comment]
https://github.com/bretterer/home-assistant-rivian/releases/tag/0.7.0-beta.3 released today fixes the underlying issue that was triggering this still doesn't support OTPs, hopefully tomorrow I'll get to building a beta.4 for that.

Yes, @dag10 the magic suffix trick for new email address works for rivian (meaning they don't block that via regex 🤫) and with gmail that or adding a random period `us.er@gmail.com` in your email username works similarly.

Closing this out now that it isn't an active issue with the latest beta release, still will be if you choose beta.1 expicitly.
