### ISSUE TITLE
Seat Heat Reporting as On Randomly

### ISSUE THREAD

**Issue by tmack8001** [bretterer/home-assistant-rivian#60]
![image](https://user-images.githubusercontent.com/2158627/223299590-a6a9f159-516b-4c6d-8490-0ece21037622.png) message in [discord](https://discord.com/channels/892997443896111105/961034025689051147/1082424662472015972)

There likely another state being returned for the rear seat heat when the truck is in sleep state that isn't properly mapped to "off" state in HA so that the seat heat returns it is active when it really isn't.

**Comment by krazos** [comment]
My R1T is currently sleeping, and I'm seeing the same issue. `Heated Seat Rear Left` and `Heated Seat Rear Right` both are showing a native value of `Fault`.

**Comment by tmack8001** [comment]
Ah, `Fault` is what we aren't mapping correctly. 

Should be able to have a fix for that fairly easily.

**Comment by tmack8001** [comment]
This will be fixed in the next release, will aim to get a release going tomorrow. Leaving open for visibility until that point.
