### ISSUE TITLE
Binary Sensors showing a fault status

### ISSUE THREAD

**Issue by jrgutier** [bretterer/home-assistant-rivian#67]
I've recently created an automation to notify me when doors lock/unlock. Saw that there would be random times, usually while the car is waking up, that it would toggle from unlocked->locked->unlocked right away. I traced it down to this:
>             }, 'closureLiftgateClosed': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'signal_not_available'
>             }, 'closureLiftgateLocked': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'unlocked'
>             }, 'closureSideBinLeftClosed': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'signal_not_available'
>             }, 'closureSideBinLeftLocked': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'signal_not_available'
>             }, 'closureSideBinRightClosed': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'signal_not_available'
>             }, 'closureSideBinRightLocked': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'signal_not_available'
>             }, 'closureTailgateClosed': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'signal_not_available'
>             }, 'closureTailgateLocked': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'signal_not_available'
>             }, 'closureTonneauClosed': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'signal_not_available'
>             }, 'closureTonneauLocked': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'signal_not_available'
>             }, 'defrostDefogStatus': {'timeStamp': '2023-03-09T03: 10: 32.929Z', 'value': 'Off'
>             }, 'doorFrontLeftClosed': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'signal_not_available'
>             }, 'doorFrontLeftLocked': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'fault'
>             }, 'doorFrontRightClosed': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'signal_not_available'
>             }, 'doorFrontRightLocked': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'fault'
>             }, 'doorRearLeftClosed': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'signal_not_available'
>             }, 'doorRearLeftLocked': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'fault'
>             }, 'doorRearRightClosed': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'signal_not_available'
>             }, 'doorRearRightLocked': {'timeStamp': '2023-03-09T03: 10: 32.399Z', 'value': 'fault'

Two ways of handling this, in my opinion.

1. If we see a fault signal ('fault', 'signal_not_available'), we can pass a None to is_on, which will show as Unavailable for a blip in HA.
2. We can use the value in _previous_vehicle_info_items to pass the last known good value.

I would be more inclined to choose the second option since I dislike having breaks in my HA history lines.

**Comment by krazos** [comment]
I would also vote in favor of preserving saved value rather than breaking up state history with random `unavailable` values.

**Comment by tmack8001** [comment]
this should be merged and released in the latest version available 0.7.4
