### ISSUE TITLE
Deprecated DevContainer

### ISSUE THREAD

**Issue by tmack8001** [bretterer/home-assistant-rivian#76]
```
This devcontainer is deprecated, plaese replace it.
https://github.com/ludeeus/container#deprecated 
```

**Comment by natekspencer** [comment]
@tmack8001 I have local changes that replace the use of this container on my box already. I can do a PR for this shortly if you haven't already started on it.

**Comment by tmack8001** [comment]
In trying to upgrade my HA I have borked my HA devcontainer. Keep getting errors on onboarding about InvalidUser though the storage is empty and never had a user.

Need to figure that out.

No haven't started work on this at all just using the prior container, maybe that is the problem?
