### ISSUE TITLE
GraphQL Vehicle State Query Deprecated

### ISSUE THREAD

**Issue by tmack8001** [bretterer/home-assistant-rivian#87]
... private API deprecated again ...

new websocket is implemented in https://github.com/bretterer/rivian-python-client/releases/tag/0.2.0

**Comment by bretterer** [comment]
We have released [0.9.0b0](https://github.com/bretterer/home-assistant-rivian/releases/tag/0.9.0b0) which fixes the deprecated API.  This will require you to update to a beta channel in HACS.

We will plan to run this beta for a few hours and will release an official version 0.9.0 around 8pm est if all goes well with testing the beta.

Please provide any feedback you have here on this ticket regarding the beta

**Comment by natekspencer** [comment]
Fixed via #88
