### ISSUE TITLE
Add support for rdata control API

### ISSUE THREAD

**Issue by patfreeman** [bretterer/home-assistant-rivian#9]
As it is, this integration is read only and cannot control the vehicle in any way. There are many controls available through the cloud rdata control API for functions like lock, unlock, A/C control, trunk, tonneau, and tail gate control. Adding support for this functionality will bring this integration more in line with the functions available in the mobile app.

**Comment by bretterer** [comment]
There are sadly some restrictions that we have not been able to get around with sending commands to the Rivian.  We are working on figuring out how to handle this, but as of right now we won't be able to support this feature.

**Comment by natekspencer** [comment]
This is now available in 1.0.0
