### ISSUE TITLE
Document Entity Renaming

### ISSUE THREAD

**Issue by tmack8001** [bretterer/home-assistant-rivian#92]
To provide an upgrade guide we should have different sensor/entity naming in a tablular layout for users to reference.

Maybe leverage some of the revision history in the dashboards to obtain this info: https://gist.github.com/tmack8001/d213097f4309a977d1806573cf2b2e91/revisions

Some members of the discord community have asked this before for instance @fletch today asked, https://discord.com/channels/892997443896111105/961034025689051147/1101322247785951232

> I don't have any `rivian_r1s_*` entities
> and (for example) my `sensor.rivian_r1t_battery_state_of_charge` equivalent seems to be `sensor.rivian_energy_storage_charger_adjusted_soc`

**Comment by natekspencer** [comment]
This is now documented in https://github.com/bretterer/home-assistant-rivian/releases#entity-mapping

Do we still want a separate guide for it or is that sufficient?
